// This file is auto-generated by scripts/generate-blog-registry.mjs.
// Do not edit it by hand.

import type { BlogPost } from "./blog-types";
import { addLiveChatToShopifyPost } from "./blog-post-add-live-chat-to-shopify";
import { afterHoursLiveChatEcommerceLeadsPost } from "./blog-post-after-hours-live-chat-ecommerce-leads";
import { bestIntercomAlternativesSmallTeamsPost } from "./blog-post-best-intercom-alternatives-small-teams";
import { bestLiveChatForStartupsPost } from "./blog-post-best-live-chat-for-startups";
import { bestLiveChatToolsSmallBusinessPost } from "./blog-post-best-live-chat-tools-small-business";
import { chatlyVsIntercomPost } from "./blog-post-chatly-vs-intercom";
import { chatlyVsZendeskPost } from "./blog-post-chatly-vs-zendesk";
import { ecommerceLiveChatSupportPost } from "./blog-post-ecommerce-live-chat-support";
import { liveChatSoftwareSmallTeamsPost } from "./blog-post-live-chat-software-small-teams";
import { liveChatVsContactFormsPost } from "./blog-post-live-chat-vs-contact-forms";
import { reduceResponseTimeUnderTwoMinutesPost } from "./blog-post-reduce-response-time-under-2-minutes";
import { wordpressLiveChatSetupPost } from "./blog-post-wordpress-live-chat-setup";

export const generatedBlogPosts: BlogPost[] = [
  addLiveChatToShopifyPost,
  afterHoursLiveChatEcommerceLeadsPost,
  bestIntercomAlternativesSmallTeamsPost,
  bestLiveChatForStartupsPost,
  bestLiveChatToolsSmallBusinessPost,
  chatlyVsIntercomPost,
  chatlyVsZendeskPost,
  ecommerceLiveChatSupportPost,
  liveChatSoftwareSmallTeamsPost,
  liveChatVsContactFormsPost,
  reduceResponseTimeUnderTwoMinutesPost,
  wordpressLiveChatSetupPost,
];
