import { check, foreignKey, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { users } from "./core";

export const seoPlanRuns = pgTable("seo_plan_runs", {
    id: text("id").primaryKey(),
    ownerUserId: text("owner_user_id").notNull(),
    actorUserId: text("actor_user_id"),
    sourceProfileSlug: text("source_profile_slug").notNull().default("chatting-default"),
    status: text("status").notNull().default("draft"),
    strategySnapshotJson: jsonb("strategy_snapshot_json").notNull().default(sql.raw("'{}'::jsonb")),
    summaryJson: jsonb("summary_json").notNull().default(sql.raw("'{}'::jsonb")),
    generatedAt: timestamp("generated_at", { withTimezone: true, mode: "date" }),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  }, (table) => ({
    seoPlanRunsActorUserIdFkey: foreignKey({ name: "seo_plan_runs_actor_user_id_fkey", columns: [table.actorUserId], foreignColumns: [users.id] }).onDelete("set null"),
    seoPlanRunsOwnerUserIdFkey: foreignKey({ name: "seo_plan_runs_owner_user_id_fkey", columns: [table.ownerUserId], foreignColumns: [users.id] }).onDelete("cascade"),
    seoPlanRunsStatusCheck: check("seo_plan_runs_status_check", sql.raw("(status = ANY (ARRAY['draft'::text, 'generating'::text, 'ready'::text, 'failed'::text, 'archived'::text]))")),
    seoPlanRunsOwnerCreatedAtIdx: index("seo_plan_runs_owner_created_at_idx").on(table.ownerUserId, table.createdAt),
    seoPlanRunsOwnerStatusUpdatedAtIdx: index("seo_plan_runs_owner_status_updated_at_idx").on(table.ownerUserId, table.status, table.updatedAt),
  }));

export const seoPlanItems = pgTable("seo_plan_items", {
    id: text("id").primaryKey(),
    runId: text("run_id").notNull(),
    ownerUserId: text("owner_user_id").notNull(),
    position: integer("position").notNull(),
    status: text("status").notNull().default("planned"),
    targetPublishAt: timestamp("target_publish_at", { withTimezone: true, mode: "date" }),
    title: text("title").notNull(),
    targetKeyword: text("target_keyword").notNull(),
    keywordCluster: text("keyword_cluster").notNull().default(""),
    searchIntent: text("search_intent").notNull().default(""),
    contentFormat: text("content_format").notNull().default("article"),
    personaSlug: text("persona_slug").notNull().default(""),
    themeSlug: text("theme_slug").notNull().default(""),
    categorySlug: text("category_slug").notNull().default(""),
    ctaId: text("cta_id").notNull().default(""),
    priorityScore: integer("priority_score").notNull().default(0),
    rationale: text("rationale").notNull().default(""),
    notes: text("notes").notNull().default(""),
    metadataJson: jsonb("metadata_json").notNull().default(sql.raw("'{}'::jsonb")),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  }, (table) => ({
    seoPlanItemsOwnerUserIdFkey: foreignKey({ name: "seo_plan_items_owner_user_id_fkey", columns: [table.ownerUserId], foreignColumns: [users.id] }).onDelete("cascade"),
    seoPlanItemsRunIdFkey: foreignKey({ name: "seo_plan_items_run_id_fkey", columns: [table.runId], foreignColumns: [seoPlanRuns.id] }).onDelete("cascade"),
    seoPlanItemsStatusCheck: check("seo_plan_items_status_check", sql.raw("(status = ANY (ARRAY['planned'::text, 'drafted'::text, 'skipped'::text, 'archived'::text]))")),
    seoPlanItemsPriorityScoreCheck: check("seo_plan_items_priority_score_check", sql.raw("(priority_score >= 0 AND priority_score <= 100)")),
    seoPlanItemsRunPositionKey: uniqueIndex("seo_plan_items_run_position_key").on(table.runId, table.position),
    seoPlanItemsOwnerRunPositionIdx: index("seo_plan_items_owner_run_position_idx").on(table.ownerUserId, table.runId, table.position),
  }));

export const seoGeneratedDrafts = pgTable("seo_generated_drafts", {
    id: text("id").primaryKey(),
    ownerUserId: text("owner_user_id").notNull(),
    actorUserId: text("actor_user_id"),
    planRunId: text("plan_run_id"),
    planItemId: text("plan_item_id"),
    status: text("status").notNull().default("draft"),
    title: text("title").notNull(),
    slug: text("slug").notNull(),
    excerpt: text("excerpt").notNull().default(""),
    subtitle: text("subtitle").notNull().default(""),
    authorSlug: text("author_slug").notNull().default(""),
    categorySlug: text("category_slug").notNull().default(""),
    publicationStatus: text("publication_status").notNull().default("draft"),
    readingTime: integer("reading_time").notNull().default(0),
    heroImagePrompt: text("hero_image_prompt").notNull().default(""),
    draftPayloadJson: jsonb("draft_payload_json").notNull().default(sql.raw("'{}'::jsonb")),
    metadataJson: jsonb("metadata_json").notNull().default(sql.raw("'{}'::jsonb")),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  }, (table) => ({
    seoGeneratedDraftsActorUserIdFkey: foreignKey({ name: "seo_generated_drafts_actor_user_id_fkey", columns: [table.actorUserId], foreignColumns: [users.id] }).onDelete("set null"),
    seoGeneratedDraftsOwnerUserIdFkey: foreignKey({ name: "seo_generated_drafts_owner_user_id_fkey", columns: [table.ownerUserId], foreignColumns: [users.id] }).onDelete("cascade"),
    seoGeneratedDraftsPlanItemIdFkey: foreignKey({ name: "seo_generated_drafts_plan_item_id_fkey", columns: [table.planItemId], foreignColumns: [seoPlanItems.id] }).onDelete("set null"),
    seoGeneratedDraftsPlanRunIdFkey: foreignKey({ name: "seo_generated_drafts_plan_run_id_fkey", columns: [table.planRunId], foreignColumns: [seoPlanRuns.id] }).onDelete("set null"),
    seoGeneratedDraftsStatusCheck: check("seo_generated_drafts_status_check", sql.raw("(status = ANY (ARRAY['draft'::text, 'ready_for_review'::text, 'approved'::text, 'scheduled'::text, 'archived'::text]))")),
    seoGeneratedDraftsPublicationStatusCheck: check("seo_generated_drafts_publication_status_check", sql.raw("(publication_status = ANY (ARRAY['draft'::text, 'scheduled'::text, 'published'::text]))")),
    seoGeneratedDraftsReadingTimeCheck: check("seo_generated_drafts_reading_time_check", sql.raw("(reading_time >= 0)")),
    seoGeneratedDraftsOwnerSlugKey: uniqueIndex("seo_generated_drafts_owner_slug_key").on(table.ownerUserId, table.slug),
    seoGeneratedDraftsOwnerStatusUpdatedAtIdx: index("seo_generated_drafts_owner_status_updated_at_idx").on(table.ownerUserId, table.status, table.updatedAt),
  }));
