import type { FormEvent } from "react";
import type { DashboardAiAssistSettings } from "@/lib/data/settings-ai-assist";
import type { DashboardTeamMember } from "@/lib/data/settings-types";
import type { ConversationStatus, ConversationSummary, ConversationThread } from "@/lib/types";

export type DashboardThreadDetailProps = {
  activeConversation: ConversationThread | null;
  loadingConversationSummary: ConversationSummary | null;
  savingEmail: boolean;
  assigningConversation?: boolean;
  sendingReply: boolean;
  updatingStatus: boolean;
  isVisitorTyping: boolean;
  isLiveDisconnected: boolean;
  teamName: string;
  teamInitials: string;
  aiAssistSettings: DashboardAiAssistSettings;
  teamMembers?: DashboardTeamMember[];
  showSidebarInline?: boolean;
  showSidebarDrawer?: boolean;
  showBackButton?: boolean;
  onSaveConversationEmail: (event: FormEvent<HTMLFormElement>) => Promise<void>;
  onConversationAssignmentChange?: (assignedUserId: string | null) => Promise<void>;
  onSendReply: (event: FormEvent<HTMLFormElement>) => Promise<void>;
  onRetryReply: (messageId: string) => Promise<void>;
  onConversationStatusChange: (status: ConversationStatus) => Promise<void>;
  onReplyComposerBlur: () => void;
  onReplyComposerFocus: (value: string) => void;
  onReplyComposerInput: (value: string) => void;
  onToggleTag: (tag: string) => Promise<void>;
  onBack?: () => void;
  onOpenSidebar?: () => void;
  onCloseSidebar?: () => void;
};
